heat_template_version: 2017-09-01

description: Heat template to create a server from a volume

parameters:
  key_name:
    description: Name of a KeyPair to enable SSH access.
    type: string
  flavor:
    description: Flavor to use.
    type: string
    default: small
  server_name:
    description: Server name string.
    type: string
  volume_size:
    description: Size of volume
    type: number
    default: 25
  extra_volume_size:
    description: Size of extra volume
    type: number
    default: 0
  extra_volume_type:
    type: string
    default: ceph-ssd
  image_id:
    description: Name or ID of the image to use.
    type: string
    default: ubuntu-focal
  net:
    description: Name of the private network.
    type: string
    default: test
  share_net:
    description: Name of the network for Manila shares.
    # if left unset then PLACEHOLDER will get removed later
    type: string
    default: PLACEHOLDER
  external_net:
    description: Name of the external network.
    type: string
    default: external
  assign_public_ip:
    type: boolean
    default: false
  server_group:
    type: string

conditions:
  public_ip: { get_param: assign_public_ip }
  extra_volume: { not: { equals: [ { get_param: extra_volume_size }, 0] } }

resources:
  vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      image: { get_param: image_id }
  srv:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      key_name: { get_param: key_name }
      flavor: { get_param: flavor }
      block_device_mapping_v2:
        - device_name: /dev/vda
          volume_id: { get_resource: vol }
          delete_on_termination: true
      networks:
        - network: test
  extra_vol:
    condition: extra_volume
    type: OS::Cinder::Volume
    properties:
      size: { get_param: extra_volume_size }
      volume_type: { get_param: extra_volume_type }
  extra_vol_attachment:
    condition: extra_volume
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: srv } 
      volume_id: { get_resource: extra_vol }
